book/urls.py
from django.urls import path, include
from book.views import *

app_name = "book"

urlpatterns = [
    path("",get_books, name="get_books"),
    path("by-isbn/<str:isbn>",get_book_by_isbn, name="get_book_by_isbn"),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('book/<int:book_id>/', book_info, name='book_info'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
]

readnow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('review/', include('review_buku.urls')),
    path('pinjam/', include('pinjam_buku.urls')),
    path('auth/', include('authentication.urls')),
]

rekomendasi/urls.py
from django.urls import path
from rekomendasi.views import *

app_name = 'rekomendasi'

urlpatterns = [
    path('similar-books/<int:id>', similar_books, name='similar_books'),
    path('json/', get_recommendations_json, name='get_recommendations_json'),
    path('json/<int:id>', get_recommendations_json_by_id, name='get_recommendations_json_by_id'),
    path('json-isbn/', get_recommendations_json_by_isbn, name='get_recommendations_json_by_isbn'),
    path('filter-books-ajax/<int:id>', filter_books_ajax, name='filter_books_ajax'),
    path('isbn-search/',isbn_search,name="isbn_search")
]

rekomendasi/models.py
from django.db import models
from book.models import Book

# Create your models here.
class BookRecommendation(models.Model):
    recommended_book = models.ForeignKey(Book, on_delete=models.CASCADE)
    source_book = models.ForeignKey(Book, related_name='recommendations', on_delete=models.CASCADE)
    recommendation_score = models.IntegerField()

    def __str__(self):
        return f"Rekomendasi {self.recommended_book.title} dari {self.source_book.title}"

rekomendasi/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.core import serializers
from book.models import Book
from wishlist.models import Wishlist
from .models import BookRecommendation
from django.views.decorators.csrf import csrf_exempt
import json



# Create your views here.
def similar_books(request, id):
    book = Book.objects.get(pk = id)

    # Periksa apakah rekomendasi sudah ada
    if not has_recommendations(book):
        init_recommend_book(book)

    selected_publish_year = request.GET.get('publishYear')
    recommendation_books = BookRecommendation.objects.filter(source_book=book)

    if selected_publish_year:
        # Jika tahun penerbitan sudah ada dalam request, maka filter berdasarkan tahun
        recommendation_books = recommendation_books.filter(
            recommended_book__publish_year=selected_publish_year
        )

    context = {"main_book" : book,
               'recommendation_books': recommendation_books}
    
    if request.user.is_authenticated:
        # do something
        wishlists = Wishlist.objects.filter(user=request.user)
        recommendation_wishlist = []

        for wishlist in wishlists:
            if not has_recommendations(wishlist.book):
                init_recommend_book(wishlist.book)
            recommendation = BookRecommendation.objects.filter(source_book=wishlist.book)[0]
            recommendation_wishlist.append(recommendation)
        
        context['recommendation_wishlist'] = recommendation_wishlist

        
    return render(request, 'similar_books.html', context)

def init_recommend_book(source_book):
    # Dapatkan buku-buku lain oleh penulis yang sama
    recommended_books = [Book.objects.get(pk = i+1) for i in source_book.get_indices_as_list()[1:]]
    distance = [int(i) for i in source_book.get_distances_as_list()[1:]]

    for index, recommended_book in enumerate(recommended_books):
        recommendation_score = distance[index]
        # Buat objek BookRecommendation
        recommendation = BookRecommendation(
            recommended_book=recommended_book,
            source_book=source_book,
            recommendation_score=recommendation_score,
        )

        # Simpan objek BookRecommendation ke dalam database
        recommendation.save()

def has_recommendations(source_book):
    # Periksa apakah ada BookRecommendation yang sudah terkait dengan source_book
    return BookRecommendation.objects.filter(source_book=source_book).exists()

def get_recommendations_json(request):
    data = BookRecommendation.objects.all()
    return HttpResponse(serializers.serialize("json",data),content_type="application/json")


@csrf_exempt
def get_recommendations_json_by_id(request, id):
    book = Book.objects.get(pk = id)

    # Periksa apakah rekomendasi sudah ada
    if not has_recommendations(book):
        init_recommend_book(book)

    recommendation_id = [i+1 for i in book.get_indices_as_list()][1:]

    recommendation_books = Book.objects.filter(pk__in=recommendation_id)

    # Request method POST
    if request.method == 'POST':
        selected_publish_year = json.loads(request.body)['publishedYear']
        if selected_publish_year:
            # Jika tahun penerbitan sudah ada dalam request, maka filter berdasarkan tahun
            recommendation_books = recommendation_books.filter(
                publish_year=selected_publish_year
            )

    
    return HttpResponse(serializers.serialize("json",recommendation_books),content_type="application/json")

@csrf_exempt
def get_recommendations_json_by_isbn(request):
    if request.method == 'GET':
        
        data = request.GET.get('isbn')
        book = Book.objects.get(isbn=data)

        # Masih perlu dicek apakah terjadi error kalau tidak ada json response status
        return get_recommendations_json_by_id(request, book.pk)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def filter_books_ajax(request, id):
    book = Book.objects.get(pk = id)

    # Periksa apakah rekomendasi sudah ada
    if not has_recommendations(book):
        init_recommend_book(book)

    selected_publish_year = request.GET.get('publishYear')
    recommendation_books = BookRecommendation.objects.filter(source_book=book)

    if selected_publish_year:
        # Jika tahun penerbitan sudah ada dalam request, maka filter berdasarkan tahun
        recommendation_books = recommendation_books.filter(
            recommended_book__publish_year=selected_publish_year
        )

    # NOTE: Masih perlu diatur tergantung kebutuhan pas di similar_book.html nantinya
    data = [{'id': rec.recommended_book.pk,
            'title': rec.recommended_book.title,
            'authors': rec.recommended_book.authors,
            'rating': rec.recommended_book.rating, 
            'image_url':rec.recommended_book.image_url}
            for rec in recommendation_books]

    return JsonResponse(data, safe=False)


@csrf_exempt
def isbn_search(request):
    if request.method == 'POST':
        isbn = request.POST.get('isbn')
        try:
            book = Book.objects.get(isbn=isbn)  # Replace with the actual model and field name
            # Use reverse to get the URL for the 'similar_books' view
            url = reverse('rekomendasi:similar_books', args=[book.id])
            # Create a JSON response with the redirect URL
            response_data = {'redirect_url': url}
            return JsonResponse(response_data)
        except Book.DoesNotExist:
            return JsonResponse({'error': 'ISBN not found'}, status=404)
    return JsonResponse({'error': 'Invalid request'}, status=400)

rekomendasi/templates/similar_books.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Font Montserrat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">

    <!-- External Stylesheet -->
    <link rel="stylesheet" type="text/css" href=" {% static 'admin/css/styles.css' %} ">

    <!-- Bootstrap -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script> -->

    <!-- Content -->
    <div class="background-purple" style="padding-bottom: 80px;">
        <nav class="navbar navbar-expand-lg">
            <div class="container mt-3">
                <a class="navbar-brand d-flex align-items-center justify-content-center" style="color:white; font-family: 'Montserrat', sans-serif;">
                    <img src="{% static 'icon-recommendation.png' %}" alt="Logo" width="50" height="40" class="d-inline-block align-text-top me-1 book-image">
                    Book Recommendation</a>

                <!-- Filter with AJAX -->
                <form id="filterForm" class="d-flex" role="search" method="get" onsubmit="return false">
                    <label class = "nav-item" for="publishYear"></label>
                    <input class="form-control me-2" placeholder="Masukkan tahun terbit" aria-label="Tahun Terbit" type="number" name="publishYear" id="publishYear" min="0" step="1">
                    <input type="button" value="Filter" class="btn btn-primary mx-1" onclick="getFilteredBooks()">
                    <a href="{% url 'rekomendasi:similar_books' main_book.id %}" class="btn btn-warning mx-1">Reset</a>
                </form>
            </div>
        </nav>

        <section class="hero" stye="padding:80px 0;">
            <div class="container">
                <div class="row">
                    <div class="row d-flex align-items-center justify-content-center">
                        <div class ="col-md-6">
                            <div class="text" style="font-family: 'Montserrat', sans-serif; font-size:40px; line-height: 50px; margin-top:30px">
                                Book Recommendations Based on<br> <p style="font-size: 20px; line-height: 30px; margin-top: 20px;">{{ main_book.title }}</p>
                            </div>
                            <div class="buttons" style="padding-top:40px">
                                <a href="#bookRec" class="btn btn-dark" style="font-weight: bold;">See Recommendations</a>
                                <button type="button" class="btn btn-warning ms-3" data-bs-toggle="modal" data-bs-target="#exampleModal" style="font-weight: bold;">Other Book Recommendations</button>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img class="icon-book-3d" src="{% static '4.png' %}" alt="book-icon" width="450" height="350" style="margin-left:80px;">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Modal Ganti Rekomendasi Buku -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Other Book Recommendations</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">ISBN:</label>
                            <input type="text" class="form-control" id="isbn" name="isbn"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_submit" data-bs-dismiss="modal">Find Recommendations</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-5 mb-5" id="book_list">
        <div class="book-grid">
            {% for recommendation in recommendation_books %}
                <div class="card" style="width: 120px;">
                    <img src="{{ recommendation.recommended_book.image_url }}" class="card-img-top" alt="{{ recommendation.recommended_book.title }}" height="180px" style="object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 12px;">{{ recommendation.recommended_book.title }}</h5>
                        <p class="card-text" style="font-size: 10px;">{{ recommendation.recommended_book.authors }}</p>
                        <a href="{% url 'main:book_info' main_book.id %}" class="btn btn-primary" id="purple-button" style="font-size: 8px; padding: 5px 10px; ">More Informations</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <hr>

    <div class="container mt-5 mb-5" id="book_list_wishlist">
        {% if user.is_authenticated %}
            <!-- Konten yang hanya ditampilkan untuk pengguna yang sudah login -->
            <h4 style="text-align: center; margin-bottom: 40px;" >Recommendations Based on Your Wishlist</h2>
            <div class="book-grid">
                {% for recommendation in recommendation_wishlist %}
                    <div class="card" style="width: 120px;">
                        <img src="{{ recommendation.recommended_book.image_url }}" class="card-img-top" alt="{{ recommendation.recommended_book.title }}" height="180px" style="object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title" style="font-size: 12px;">{{ recommendation.recommended_book.title }}</h5>
                            <p class="card-text" style="font-size: 10px;">{{ recommendation.recommended_book.authors }}</p>
                            <a href="{% url 'main:book_info' main_book.id %}" class="btn btn-primary" id="purple-button" style="font-size: 8px; padding: 5px 10px; ">More Informations</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            
        {% else %}
            <!-- Konten yang hanya ditampilkan untuk pengguna yang belum login -->
            <p style="text-align: center;">Please <a href="{% url 'main:login' %}">login</a> to see recommendations based on your wishlist.</p>
        {% endif %}
    </div>

    

    <script>
        async function getFilteredBooks() {
            const selectedYear = document.getElementById('publishYear').value;
            const url = `{% url 'rekomendasi:filter_books_ajax' main_book.id %}?publishYear=${selectedYear}`;
            
            const response = await fetch(url);
            if (response.ok) {
                document.getElementById("book_list").innerHTML = ""
                const books = await response.json();

                let htmlString = `<div class="container mt-5" id="book_list">
                    <div class="book-grid">`
                    books.forEach((book) => {
                        htmlString += `\n<div class="card" style="width: 120px;">
                                        <img src="${book.image_url}" class="card-img-top" alt="${book.title}" height="180px" style="object-fit: cover;">
                                        <div class="card-body">
                                            <h5 class="card-title" style="font-size: 12px;">${book.title}</h5>
                                            <p class="card-text" style="font-size: 10px;">${book.authors}</p>
                                            <a href="#" class="btn btn-primary" id="purple-button" style="font-size: 8px; padding: 5px 10px; ">More Informations</a>
                                        </div>
                                    </div>
                            </div>
                        </div>`
                    })
                    
                    document.getElementById("book_list").innerHTML = htmlString
            } else {
                alert('Failed to fetch filtered books.');
            }
        }

        // Find ISBM Form -> Melakukan redirect ke halaman rekomendasi buku yang diinginkan
        function findIsbn() {
            fetch("{% url 'rekomendasi:isbn_search' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(response => {
                if (response.ok) {
                    return response.json(); // Parse the JSON response
                } else {
                    // Handle error response
                    document.getElementById("form").reset(); // Reset the form
                    alert('ISBN not found or an error occurred.');
                }
            }).then(data => {
                if (data.redirect_url) {
                    // Redirect to the specified URL
                    window.location.href = data.redirect_url;
                }
            });
            return false;
        }

        document.getElementById("button_submit").onclick = findIsbn;

    </script>

{% endblock content %}