book/urls.py
from django.urls import path, include
from book.views import *

app_name = "book"

urlpatterns = [
    path("",get_books, name="get_books"),
    path("by-isbn/<str:isbn>",get_book_by_isbn, name="get_book_by_isbn"),
]

readnow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('review/', include('review_buku.urls')),
    path('pinjam/', include('pinjam_buku.urls')),
    path('auth/', include('authentication.urls')),
]

wishlist/urls.py
from django.urls import path
from .views import *

app_name = 'wishlist'

urlpatterns = [
    # Flutter
    path('remove-wishlist-flutter/<int:book_id>/', remove_wishlist_flutter, name='remove_wishlist_flutter'),
    path('add-wishlist-flutter/<int:book_id>/', add_wishlist_flutter, name='add_wishlist_flutter'),
    # CRUD
    path('add-book/<int:book_id>/', add_book, name='add_book'),
    path('remove-book/<int:book_id>/', remove_book, name='remove_book'),
    path('get-book-object/<int:book_id>/', get_book_object, name='get_book_object'),
    # wishlist
    path('search-book/<str:isbn>', search_book, name='search_book'),
    path('get-wishlist/', get_wishlist_json, name='get_wishlist_json'),
    path('my-wishlist/', show_whishlist, name='show_whishlist'),
    # book list
    path('get-books/', get_books_json, name='get_books_json'),
    path('', show_books, name='show_books'),
]

book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    book_id = models.IntegerField(null=True, blank=True)
    title = models.CharField(null=True, blank=True, max_length = 255)
    num_of_pages = models.IntegerField(null=True, blank=True)
    language = models.CharField(null=True, blank=True, max_length = 255)
    authors = models.CharField(null=True, blank=True, max_length = 255)
    publisher = models.CharField(null=True, blank=True, max_length = 255)
    isbn = models.CharField(null=True, blank=True, max_length = 255)
    counts_of_review = models.IntegerField(null=True, blank=True)
    rating_dist_total = models.IntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    rating_dist1 = models.IntegerField(null=True, blank=True)
    rating_dist2 = models.IntegerField(null=True, blank=True)
    rating_dist3 = models.IntegerField(null=True, blank=True)
    rating_dist4 = models.IntegerField(null=True, blank=True)
    rating_dist5 = models.IntegerField(null=True, blank=True)
    indices = models.CharField(null=True, blank=True, max_length = 700)
    distance =  models.CharField(null=True, blank=True, max_length = 700)
    image_url = models.URLField(null=True, blank=True)
    small_image_url = models.URLField(null=True, blank=True)
    publish_day = models.IntegerField(null=True, blank=True)
    publish_month = models.IntegerField(null=True, blank=True)
    publish_year = models.IntegerField(null=True, blank=True)
    status = models.CharField(
        max_length=10,
        choices=[
            ("Available", "a"),
            ("Borrowed", "b")
        ], default="Available"
    )
    return_date = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)

    def get_indices_as_list(self):
        # Memisahkan string berdasarkan koma dan mengonversi ke integer
        return [int(index) for index in self.indices.split(',')]
    
    def get_distances_as_list(self):
        # Memisahkan string berdasarkan koma dan mengonversi ke integer
        return [float(index) for index in self.distance.split(',')]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

# Create your models here.
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

book/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers

from book.models import Book

def get_books(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json",data),content_type="application/json")

# Create your views here.
def get_book_by_isbn(request,isbn):
    data = Book.objects.filter(isbn=isbn)
    return HttpResponse(serializers.serialize("json",data),content_type="application/json")

wishlist/views.py
from django.shortcuts import render
from book.models import Book
from .models import Wishlist
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotFound
from django.core import serializers
import json
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user

# Create your views here.

# ========== Views for wishlist ==========
# search book by isbn
def search_book(request, isbn):
    # cek apakah ada di database
    # hapus huruf a pada isbn
    book = Book.objects.filter(isbn=isbn)
    book = book[0]
    temp = {
        'pk': book.pk,
        'title': book.title,
        'num_of_pages': str(book.num_of_pages),
        'language': book.language,
        'authors': book.authors,
        'publisher': book.publisher,
        'isbn': book.isbn,
        'image_url': book.image_url,
        'small_image_url': book.small_image_url,
        'publish_day': str(book.publish_day),
        'publish_month': str(book.publish_month),
        'publish_year': str(book.publish_year),
    }
    return HttpResponse(json.dumps(temp), content_type="application/json")


def show_whishlist(request):
    # Menampilkan wishlist by user
    wishlists = Wishlist.objects.filter(user=request.user)
    context = {
        'my_wishlist': wishlists
    }
    return render(request, 'wishlist.html', context)

def get_wishlist_json(request):
    # Mengambil semua object wishlist by user
    wishlist = Wishlist.objects.filter(user=request.user)
    books = [wish.book for wish in wishlist]
    return HttpResponse(serializers.serialize("json",books),content_type="application/json")

# ==================== Flutter ====================
@login_required(login_url='/login')
@csrf_exempt
def add_wishlist_flutter(request, book_id):
    if request.method == 'POST':
        # Ambil buku yang sesuai dengan book_id
        book = Book.objects.get(pk=book_id)
        user = request.user
        # Cek apakah buku sudah ada di wishlist
        if Wishlist.objects.filter(user=user, book=book).exists():
            # Kirim status bahwa data sudah ada
            return JsonResponse({"status": "existed"}, status=200)
        wishlist = Wishlist(user=user, book=book)
        wishlist.save()
        return JsonResponse({"status": "success"}, status=201)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='/login')
@csrf_exempt
def remove_wishlist_flutter(request, book_id):
    book = Book.objects.get(pk=book_id)
    user = get_user(request)
    if Wishlist.objects.filter(user=user, book=book).exists():
        # Kirim status bahwa data sudah ada
        wishlist = Wishlist.objects.get(user=user, book=book)
        wishlist.delete()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "not found"}, status=404)

# ---------- Views for CRUD ----------
def remove_book(request, book_id):
    book = Book.objects.get(pk=book_id)
    user = request.user
    wishlist = Wishlist.objects.get(user=user, book=book)
    wishlist.delete()
    return HttpResponseRedirect('')

# get book object
def get_book_object(request, book_id):
    book = Book.objects.get(pk=book_id)
    # mengambil semua atribut buku dan mengubah non string menjadi string dengan str()
    temp = {
        'book_id': book.book_id,
        'title': book.title,
        'num_of_pages': book.num_of_pages,
        'language': book.language,
        'authors': book.authors,
        'publisher': book.publisher,
        'isbn': book.isbn,
        'counts_of_review': book.counts_of_review,
        'rating_dist_total': book.rating_dist_total,
        'rating': book.rating,
        'rating_dist1': book.rating_dist1,
        'rating_dist2': book.rating_dist2,
        'rating_dist3': book.rating_dist3,
        'rating_dist4': str(book.rating_dist4),
        'rating_dist5': book.rating_dist5,
        'indices': book.indices,
        'distance': book.distance,
        'image_url': book.image_url,
        'small_image_url': book.small_image_url,
        'publish_day': book.publish_day,
        'publish_month': book.publish_month,
        'publish_year': book.publish_year,
        'status': book.status,
        'return_date': book.return_date
    }
    return JsonResponse(temp)


# ========== Views for books ==========
def show_books(request):
    # ambil semua objek buku
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'books.html', context)

def get_books_json(request):
    # Mengambil semua object buku
    books = Book.objects.all()
    return HttpResponse(serializers.serialize("json",books),content_type="application/json")
# ---------- Views for CRUD ----------
def add_book(request, book_id):
    book = Book.objects.get(pk=book_id)
    user = request.user
    # cek apakah buku sudah ada di wishlist
    if Wishlist.objects.filter(user=user, book=book).exists():
        return HttpResponseRedirect('')
    wishlist = Wishlist(user=user, book=book)
    wishlist.save()
    return HttpResponseRedirect('')

wishlist/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="">Add Books to Your Wishlist!</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/wishlist/my-wishlist/">My Wishlist</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" id="search_bar" placeholder="Search book by isbn" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit" onclick="search_book()">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <br>


    
    <div class="container">
        <div class="row row-cols-1 g-4" id="wishlist_body_card">
            <!-- diisi dengan refreshProducts -->
        </div>
    </div>


















    
    <script>
        // ======== Search Book ========
        async function search_book(){
            let isbn = document.getElementById("search_bar").value
            const book = await getBookObject(isbn)
            document.getElementById("wishlist_body_card").innerHTML = ""
            htmlString = `
                <div class="col-12 col-md-6 col-lg-3" id="card_book">
                    <div class="card text-center">
                        <div class="card-header">
                            <h5 class="card-title">
                                ${ book.title }
                            </h5>
                        </div>
                        <div class="card-body">
                            <img src="${ book.image_url }" alt=""><br>
                            <table>
                                <tr>Pages</tr>
                                <tr>: ${ book.num_of_pages }</tr>
                            </table>
                            <table>
                                <tr>ISBN Number</tr>
                                <tr>: ${ book.isbn }</tr>
                            </table>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary" id="button_add" onclick="add_book(${ book.pk })">Add wishlist</button>
                        </div>
                    </div>
                </div>
            `
            document.getElementById("wishlist_body_card").innerHTML = htmlString
        }
        async function getBookObject(isbn) {
            return fetch("{% url 'wishlist:search_book' 0 %}".replace("0", isbn)).then((res) => res.json())
        }


        // ======== Add Product ========
        function add_book(book_id){
            const newURL = "{% url 'wishlist:add_book' 0 %}".replace("0", book_id);
            fetch(newURL, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": "{{ csrf_token }}"
                },
            }).then(
                refreshBooks()
            )
        }


        // ======== Refresh Product ========
        async function getAllBooks() {
            return fetch("{% url 'wishlist:get_books_json' %}").then((res) => res.json())
        }
        async function refreshBooks() {
            document.getElementById("wishlist_body_card").innerHTML = ""
            const books = await getAllBooks()
            let htmlString = ``
            books.forEach((book) => {
                htmlString += `\n
                <div class="col-12 col-md-6 col-lg-3" id="card_book">
                    <div class="card text-center">
                        <div class="card-header">
                            <h5 class="card-title">
                                ${ book.fields.title }
                            </h5>
                        </div>
                        <div class="card-body">
                            <img src="${ book.fields.image_url }" alt=""><br>
                            <table>
                                <tr>Pages</tr>
                                <tr>: ${ book.fields.num_of_pages }</tr>
                            </table>
                            <table>
                                <tr>ISBN Number</tr>
                                <tr>: ${ book.fields.isbn }</tr>
                            </table>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary" id="button_add" onclick="add_book(${book.pk})">Add wishlist</button>
                        </div>
                    </div>
                </div>
                `
            });
            document.getElementById("wishlist_body_card").innerHTML = htmlString
        }
        refreshBooks()
    </script>
{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
{% endblock meta %}
{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="">My Wishlist</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="../">Back to add Book</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>



    <div class="container">
        <div class="row row-cols-1 g-4" id="wishlist_body_card">
            <!-- diisi dengan refreshProducts -->
        </div>
    </div>
    <script>
        // ======== Remove Book ========
        function remove_book(book_id){
            console.log(book_id)
            const newURL = "{% url 'wishlist:remove_book' 0 %}".replace("0", book_id);
            fetch(newURL, {
                method: "DELETE",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": "{{ csrf_token }}"
                },
            }).then(
                //reload this page
                location.reload()
            )
        }



        // ======== Refresh Books ========
        async function getMyWishlist() {
            return fetch("{% url 'wishlist:get_wishlist_json' %}").then((res) => res.json())
        }
        async function refreshMyWishlist() {
            document.getElementById("wishlist_body_card").innerHTML = ""
            const my_wishlist = await getMyWishlist()
            let htmlString = ``
            my_wishlist.forEach((book) => {
                htmlString += `\n
                <div class="col-12 col-md-6 col-lg-3" id="card_book">
                    <div class="card text-center">
                        <div class="card-header">
                            <h5 class="card-title">
                                ${ book.fields.title }
                            </h5>
                        </div>
                        <div class="card-body">
                            <img src="${ book.fields.image_url }" alt=""><br>
                            <table>
                                <tr>Pages</tr>
                                <tr>: ${ book.fields.num_of_pages }</tr>
                            </table>
                            <table>
                                <tr>ISBN Number</tr>
                                <tr>: ${ book.fields.isbn }</tr>
                            </table>
                        </div>
                        <div class="card-footer">
                            <button type="button" class="btn btn-danger" id="button_remove" onclick="remove_book(${book.pk})">Remove book from wishlist</button>
                        </div>
                    </div>
                </div>
                `
            });
            if (htmlString ===``){
                htmlString = `\n
                <center>
                    <h1 style="font-size:250%; padding-top:100px;">No book in wishlist</h1>
                </center>
                `
            }
            document.getElementById("wishlist_body_card").innerHTML = htmlString
        }        
        refreshMyWishlist()
    </script>
{% endblock content %}