book/urls.py
from django.urls import path, include
from book.views import *

app_name = "book"

urlpatterns = [
    path("",get_books, name="get_books"),
    path("by-isbn/<str:isbn>",get_book_by_isbn, name="get_book_by_isbn"),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('book/<int:book_id>/', book_info, name='book_info'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
]

pinjam_buku/urls.py
from django.urls import path
from .views import *

app_name = 'pinjam_buku'

urlpatterns = [
    path('get-borrowed-book/', get_borrowed_book_json, name='get_borrowed_book_json'),
    path('get-borrowed-bookk/', get_borrowed_book_jsonn, name='get_borrowed_book_jsonn'),
    path('borrow-book-ajax/<int:id>', borrow_book_ajax, name='borrow_book_ajax'),
    path('borrowed-books/', borrowed_books, name='borrowed_books'),
    path('return-book-ajax/<int:id>', return_book_ajax, name='return_book_ajax'),
    path('return-book-flutter/<int:id>/', return_book_flutter, name='return_book_flutter'),
    path('borrow-flutter/<int:book_id>/', borrow_flutter, name='borrow_flutter'), 
]

readnow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('review/', include('review_buku.urls')),
    path('pinjam/', include('pinjam_buku.urls')),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0"
            />
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
            <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        {% endblock meta %}
        <!-- Font Montserrat -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">
        
        <!-- External Stylesheet -->
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/styles.css' %}">
        
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
       
        <!-- Tailwind -->
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.15/dist/tailwind.min.css" rel="stylesheet">
    </head>

    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
<nav class="bg-#F5F5F5 p-4">
    <div class="container mx-auto d-flex justify-content-between align-items-center">
        <a href="{% url 'main:show_main' %}" class="text-dark font-bold text-xl">ReadNow</a>
        <div class="d-flex align-items-center">
            {% if user.is_authenticated %}
                <a href="/wishlist" class="mx-2">Add Wishlist</a>
                <a href="{% url 'pinjam_buku:borrowed_books' %}" class="mx-2">Borrowed Books</a>
                <a href="{% url 'main:logout' %}" class="btn btn-dark mx-2 rounded">Logout</a>
            {% else %}
                <a href="{% url 'main:login' %}" class="mx-2">Login</a>
                <a href="{% url 'main:register' %}" class="btn btn-dark mx-2 rounded">Sign Up</a>
            {% endif %}
        </div>
    </div>
</nav>