book/urls.py
from django.urls import path, include
from book.views import *

app_name = "book"

urlpatterns = [
    path("",get_books, name="get_books"),
    path("by-isbn/<str:isbn>",get_book_by_isbn, name="get_book_by_isbn"),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('book/<int:book_id>/', book_info, name='book_info'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
]

pinjam_buku/urls.py
from django.urls import path
from .views import *

app_name = 'pinjam_buku'

urlpatterns = [
    path('get-borrowed-book/', get_borrowed_book_json, name='get_borrowed_book_json'),
    path('get-borrowed-bookk/', get_borrowed_book_jsonn, name='get_borrowed_book_jsonn'),
    path('borrow-book-ajax/<int:id>', borrow_book_ajax, name='borrow_book_ajax'),
    path('borrowed-books/', borrowed_books, name='borrowed_books'),
    path('return-book-ajax/<int:id>', return_book_ajax, name='return_book_ajax'),
    path('return-book-flutter/<int:id>/', return_book_flutter, name='return_book_flutter'),
    path('borrow-flutter/<int:book_id>/', borrow_flutter, name='borrow_flutter'), 
]

readnow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/books/', include('book.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('review/', include('review_buku.urls')),
    path('pinjam/', include('pinjam_buku.urls')),
    path('auth/', include('authentication.urls')),
]

rekomendasi/urls.py
from django.urls import path
from rekomendasi.views import *

app_name = 'rekomendasi'

urlpatterns = [
    path('similar-books/<int:id>', similar_books, name='similar_books'),
    path('json/', get_recommendations_json, name='get_recommendations_json'),
    path('json/<int:id>', get_recommendations_json_by_id, name='get_recommendations_json_by_id'),
    path('json-isbn/', get_recommendations_json_by_isbn, name='get_recommendations_json_by_isbn'),
    path('filter-books-ajax/<int:id>', filter_books_ajax, name='filter_books_ajax'),
    path('isbn-search/',isbn_search,name="isbn_search")
]

main/models.py
from django.db import models
from book.models import Book

class HomePage(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE) # one-to-many

    def __str__(self):
        return self.book.title  # book title as the string representation

    class Meta:
        verbose_name = "Homepage"
        verbose_name_plural = "Homepage"

main/views.py
import datetime
import math
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.shortcuts import redirect
from book.models import Book
from pinjam_buku.views import *

#@login_required(login_url='/login')
def show_main(request):
    books = Book.objects.all()  # Retrieve all books from the database

    rows = math.ceil(len(books) / 3)
    bookdata = []

    for i in range(1, rows + 1):
        bookdata.append(books[(i - 1) * 3: i * 3])

    context = {
        'name': request.user.username,
        'app': 'ReadNow',
        'bookdata': bookdata,
    }

    return render(request, 'main.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('main:login')

def book_info(request, book_id):
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        return render(request, 'not_found.html')

    context = {
        'name': request.user.username,
        'book': book,
    }
    return render(request, 'book_info.html', context)

def show_xml(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/book_info.html
{% extends 'base.html' %}

{% block content %}
    <div>
    <a href="javascript:history.go(-1);" class="btn btn-link text-dark ml-6">Back</a>
    </div>  
    <div class="container mx-auto text-center mt-8">  
        <h1 class="text-2xl font-bold mb-4">{{ book.title }}</h1>
        <div class="flex justify-center">
            <img src="{{ book.image_url }}" alt="{{ book.title }} Cover" class="book-image mb-4">
        </div>
        <p class="mb-2">Author: {{ book.authors }}</p>
        <p class="mb-2">Number of Pages: {{ book.num_of_pages }}</p>
        <p class="mb-2">ISBN: {{ book.isbn }}</p>
        <p class="mb-2">Publisher: {{ book.publisher }}</p>
        <p class="mb-2">Rating: {{ book.rating }}</p>
        <p id="status_buku" class="mb-4">Status: {{ book.status }}</p>

        <div class="flex justify-center">
            <a href="{% url 'rekomendasi:similar_books' book.pk %}">
                <button class="btn btn-dark mx-4 mb-4 rounded">Recommendation</button>
            </a>
            <a href="{% url 'reviews_for_book' book.pk %}">
                <button class="btn btn-dark mx-4 mb-4 rounded">Book Review</button>
            </a>
        </div>
    </div>

    {% if user.is_authenticated %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Borrow a Book</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="returnDate">Set Return Date</label>
                            <input type="date" class="form-control" id="returnDate" name="return_date">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn btn-dark mx-2 rounded" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn btn-dark mx-4 rounded" id="button_borrow" data-bs-dismiss="modal" data-book-id="{{ book.pk }}">Borrow This Book</button>
                </div>
            </div>
        </div>
    </div>
    <div class="flex justify-center">
        <button type="button" class="btn btn-dark mx-4 rounded" data-bs-toggle="modal" data-bs-target="#exampleModal" id="button_pinjam">Borrow This Book</button>
    </div>
    {% endif %}
</body>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    async function getBooks() {
        const bookId = document.querySelector('#button_borrow').getAttribute('data-book-id');
        return fetch(`/json/${bookId}`).then((res) => res.json())
    }

    async function refreshBook() {
        const book = await getBooks();
        console.log(book[0].fields.status)

        const bookStatus = document.getElementById("status_buku");
        const buttonPinjam = document.getElementById('button_pinjam');
        const borrowButton = document.getElementById('button_borrow');

        if (book[0].fields.status === 'Available') {
            bookStatus.textContent = 'Status: Available';
            borrowButton.textContent = 'Borrow Book';
            buttonPinjam.textContent = 'Borrow Book';
        } else {
            bookStatus.textContent = `Will be available at: ${book[0].fields.return_date}`;
            borrowButton.textContent = 'Return Book';
            buttonPinjam.textContent = 'Borrowed';
            buttonPinjam.disabled = true;
        }
    }
    refreshBook();

    function borrowBook(bookId) {
        const book = getBooks();
        fetch(`{% url 'pinjam_buku:borrow_book_ajax' book.pk %}`, {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshBook)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_borrow").onclick = function() {  
        const bookId = document.querySelector('#button_borrow').getAttribute('data-book-id'); 
        borrowBook(bookId);
    }



</script>

{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Login</h1>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Login</button>
                    </form>
                    {% if messages %}
                        <ul class="mt-3">
                            {% for message in messages %}
                                <li class="alert alert-danger">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <p class="mt-3 text-center">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Font Montserrat -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@800&display=swap" rel="stylesheet">

<!-- External Stylesheet -->
<link rel="stylesheet" type="text/css" href=" {% static 'admin/css/styles.css' %} ">

<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<style>
    .flex.items-left {
    justify-content: flex-start;
}

.flex.items-left .flex {
    margin-right: 10px; /* Adjust the spacing between search input and button as needed */
}

#sort {
    margin-left: 10px; /* Adjust the spacing between search button and sort dropdown as needed */
}

</style>


    <!-- Content -->
    <div class="background-purple" style="padding-bottom: 80px;">
        <nav class="navbar navbar-expand-lg">
            <div class="container mt-3">
                <a class="navbar-brand d-flex align-items-center justify-content-center" style="color:white; font-family: 'Montserrat', sans-serif;">
                    <img src="{% static 'icon-recommendation.png' %}" alt="Logo" width="50" height="40" class="d-inline-block align-text-top me-1 book-image">
                    </a>
            </div>
        </nav>

        <section class="hero" stye="padding:80px 0;">
            <div class="container">
                <div class="row">
                    <div class="row d-flex align-items-center justify-content-center">
                        <div class ="col-md-6">
                            <div class="text" style="font-family: 'Montserrat', sans-serif; font-size:40px; line-height: 50px; margin-top:30px">
                                List of Books<br>
                            </div>
                            <div class="buttons" style="padding-top:40px">
                                <div class="flex justify-center items-left mt-4">
                                    <div class="flex">
                                        <input type="text" placeholder="Search..." class="rounded-l-md p-2 border border-gray-300 focus:ring-2 focus:ring-blue-500">
                                        <button class="bg-blue-500 text-white rounded-r-md p-2">Search</button>
                                    </div>
                                    <label for="sort" class="text-white-600">Sort by:</label>
                                    <select id="sort" name="sort" class="rounded-md p-2 border border-gray-300 focus:ring-2 focus:ring-blue-500">
                                        <option value="title">Alphabetic</option>
                                        <option value="rating">Rating</option>
                                        <option value="pages">Number of Pages</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img class="icon-book-3d" src="{% static '4.png' %}" alt="book-icon" width="450" height="350" style="margin-left:80px;">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="flex justify-center">
        <div class="w-full max-w-screen-xl">
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {% for row in bookdata %}
                    <div class="p-4">
                        <ul class="book-list">
                            {% for book in row %}
                                <li class="book-details bg-white p-4 shadow-md rounded-md">
                                    <h3 class="text-lg font-semibold">{{ book.title }}</h3>
                                    <p class="text-gray-600">Author: {{ book.authors }}</p>
                                    <p class="text-gray-600">Number of Pages: {{ book.num_of_pages }}</p>
                                    <p class="text-gray-600">Rating: {{ book.rating }}</p>
                                    <img src="{{ book.image_url }}" alt="{{ book.title }} Cover" class="book-image mb-4">
                                    <a href="{% url 'main:book_info' book.id %}">
                                        <button class="bg-blue-500 text-white py-2 px-4 rounded-md">Book Information</button>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/not_found.html
<h1>Book not found!</h1>

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1 class="text-2xl font-bold mb-4">Register</h1> 

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Sign Up"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}